version: "3"

services:
  syslog:
    build: syslog
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp:/var/log/
    restart: on-failure

  noise:
    build: noise
    extends:
      file: base.yml
      service: base
    depends_on:
      - syslog
    restart: on-failure

  beats:
    build: beats
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp/messages-kv.log:/var/log/messages
      - ./tmp:/var/beats
    depends_on:
      - syslog
      - noise
      - bootstrap
    restart: on-failure

  logstash:
    build: logstash
    extends:
      file: base.yml
      service: base
    ports:
      - 5044:5044
    restart: on-failure
    depends_on:
      - bootstrap
      - beats
    volumes:
      - ./tmp:/var/log/

  kibana:
    build: kibana
    extends:
      file: base.yml
      service: base
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://ec2-13-53-46-140.eu-north-1.compute.amazonaws.com:9200
    restart: on-failure

  rabbitmq:
    build: rabbitmq
    extends:
      file: base.yml
      service: base
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  bootstrap:
    extends:
      file: base.yml
      service: base
    build: bootstrap
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
    environment:
      - BROKERS=kafka,rabbitmq

  zookeeper:
    build: zookeeper
    extends:
      file: base.yml
      service: base
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    build: kafka
    extends:
      file: base.yml
      service: base
    ports:
      - "9092:9092"
      - "9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    healthcheck:
      test: "exit 0"

  kafdrop:
    build: kafdrop
    extends:
      file: base.yml
      service: base
    restart: "on-failure"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka
