version: "3"

services:
  syslog:
    build: syslog
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp:/var/log/
    restart: on-failure

  noise:
    build: noise
    extends:
      file: base.yml
      service: base
    depends_on:
      - syslog
    restart: on-failure

  beats:
    build: beats
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp/messages-kv.log:/var/log/messages
      - ./tmp:/var/beats
    depends_on:
      - noise
      - logstash
    restart: on-failure

  logstash:
    build: logstash
    ports:
      - 5044:5044
    restart: on-failure

  elasticsearch:
    build: elasticsearch
    ports:
      - 9200:9200
    depends_on:
      - logstash
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    restart: on-failure

  kibana:
    build: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: on-failure
