version: "3"

services:
  syslog:
    build: syslog
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp:/var/log/
    restart: on-failure

  noise:
    build: noise
    extends:
      file: base.yml
      service: base
    depends_on:
      - syslog
    restart: on-failure

  beats:
    build: beats
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp/messages-kv.log:/var/log/messages
      - ./tmp:/var/beats
    depends_on:
      - noise
      - kafka
      - rabbitmq
    restart: on-failure

  logstash:
    build: logstash
    ports:
      - 5044:5044
    restart: on-failure
    depends_on:
      - rabbitmq
      - kafka
      - elasticsearch

  elasticsearch:
    build: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    restart: on-failure

  kibana:
    build: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: on-failure

  rabbitmq:
    build: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  bootstrap:
    extends:
      file: base.yml
      service: base
    build: bootstrap
    depends_on:
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
    restart: on-failure

  zookeeper:
    build: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    build: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    healthcheck:
      test: "exit 0"

  kafdrop:
    build: kafdrop
    restart: "on-failure"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka
