version: "3"

services:
  syslog:
    build: syslog
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp:/var/log/

  noise:
    build: noise
    extends:
      file: base.yml
      service: base
    depends_on:
      - syslog
