version: "3"

services:
  syslog:
    build: syslog
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp:/var/log/

  noise:
    build: noise
    extends:
      file: base.yml
      service: base
    depends_on:
      - syslog

  beats:
    build: beats
    extends:
      file: base.yml
      service: base
    volumes:
      - ./tmp/messages-kv.log:/var/log/messages
      - ./tmp:/var/beats
    depends_on:
      - noise

  logstash:
    build: logstash
    ports:
      - 5044:5044
    volumes:
      - ./tmp/logstash:/opt/kalai
