filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /var/log/messages
      - /var/log/yum.log
      - /var/log/grubby_prune_debug

# output.file:
#   path: "/var/beats"
#   filename: beats

output.logstash:
  hosts: ["logstash:5044"]
